# Generated by Django 5.2.17 on 2026-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=30),
        ),
    ]
