# Generated by Django 5.2.17 on 2026-10-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumebuilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
